class Configuration:
    ENABLE = False

    ACCESS_LOG_SERVICE_ENABLE = False
    ERROR_LOG_SERVICE_ENABLE = False

    DEFAULT_LOGGER_TYPE = ['ROTATING FILE LOGGER','FILE LOGGER','CONSOLE LOGGER','DB LOGGER']

    LOGGER_TYPE = 'CONSOLE LOGGER'
    